version: '3.8'
services:
 
  app:
    build:
      context: .
      dockerfile: dockerfile.openai
    container_name: processor-app
    volumes:
      - .:/app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
  
    command: sleep infinity
    tty: true
    stdin_open: true

  

  