# Use an official Python runtime as a parent image
FROM python:3.12.11-slim-bookworm

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY requirements.txt requirements.txt

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY . .



# Define environment variable


# Run app.py when the container launches
#CMD ["python", "./src/check-ollama.py"]
CMD ["python", "./src/process-with-openai.py"]